export const LOGIN = 'LOGIN';
export const INIT_SERVER = 'INIT_SERVER';
export const FETCH_RAPID_VIEWS = 'FETCH_RAPID_VIEWS';
export const FETCH_RAPID_VIEWS_CONFIG = 'FETCH_RAPID_VIEWS_CONFIG';
export const FETCH_BOARD_WORK_ALLDATA = 'FETCH_BOARD_WORK_ALLDATA';
export const FETCH_BOARD_ISSUE_DETAILS = 'FETCH_BOARD_ISSUE_DETAILS';